### ISSUE TITLE
Pull in tests from my repo

### ISSUE THREAD

**Issue by dexterlohnes** [kinfoundation/StellarKit#2]
Hi all,

I've done a not totally insignificant amount of work on my own implementation of a Swift SDK for Stellar. I'd recommend you take what work you can from there. I could also probably find some time to issue a PR. My repo is [here](https://github.com/dexterlohnes/swift-stellar-sdk). 

Tests, specifically, can be found [here]( https://github.com/dexterlohnes/swift-stellar-sdk/tree/master/StellarSDKTests)

Would be happy to put some time in on the SDK where I can. Are you planning on submitting to the SBC?

**Comment by dexterlohnes** [comment]
I'll just

**Comment by avi-kik** [comment]
I don't know what plans we have with respect to the SBC.  I looked over your unit tests, and I don't see anything that would translate.  Almost by definition, unit tests are tied to the implementation, and we have very different implementations.

For one, you seem to have concentrated on key-pair handling.  In `StellarKit`, key-pair handling is delegated to an external provider, via a protocol.  `StellarKit` itself does not generate key-pairs, nor does it sign anything.  While it's true that `KeyUtils` is a part of `StellarKit`, it is adequately tested by successfully testing the APIs which use its functions.

**Comment by avi-kik** [comment]
If you would like to contribute to the code base, I would love to see what you come up with.  `StellarKit` is intended to underlie our `KinSDK`, and functionality is limited to what is required.  Turning `StellarKit` into a complete implementation of the Horizon API is not our goal, but we welcome Pull Requests in that direction.

**Comment by dexterlohnes** [comment]
Thanks for the reply Avi! Good to know the project isn't aimed at being a full port of the Stellar SDK. I know when awareness of your repo first popped up in the public Stellar Slack chat there was an assumption that this was going to be what it was.
